// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHKIiHVB1IjG1lPkWQqIODIHbkyIzXPA',
    appId: '1:1056635205913:web:c118f58cc77a746f412d88',
    messagingSenderId: '1056635205913',
    projectId: 'weartoweather',
    authDomain: 'weartoweather.firebaseapp.com',
    storageBucket: 'weartoweather.firebasestorage.app',
    measurementId: 'G-WC451Z655Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhwWrBagWsqGtXL5N4z1EYv5ZClxHPbz0',
    appId: '1:1056635205913:android:7ce01f47992b8018412d88',
    messagingSenderId: '1056635205913',
    projectId: 'weartoweather',
    storageBucket: 'weartoweather.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ80tiLB07h-N3Ef4qHADxlgd05nSBhzk',
    appId: '1:1056635205913:ios:d81df1d76ae9122e412d88',
    messagingSenderId: '1056635205913',
    projectId: 'weartoweather',
    storageBucket: 'weartoweather.firebasestorage.app',
    iosBundleId: 'com.example.wear2weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ80tiLB07h-N3Ef4qHADxlgd05nSBhzk',
    appId: '1:1056635205913:ios:d81df1d76ae9122e412d88',
    messagingSenderId: '1056635205913',
    projectId: 'weartoweather',
    storageBucket: 'weartoweather.firebasestorage.app',
    iosBundleId: 'com.example.wear2weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVHKIiHVB1IjG1lPkWQqIODIHbkyIzXPA',
    appId: '1:1056635205913:web:1edf471eb99091d7412d88',
    messagingSenderId: '1056635205913',
    projectId: 'weartoweather',
    authDomain: 'weartoweather.firebaseapp.com',
    storageBucket: 'weartoweather.firebasestorage.app',
    measurementId: 'G-7CGLMF1JBT',
  );
}
